dotnet restore Server\ServerFunctions\extensions.csproj
dotnet build Server\ServerFunctions\extensions.csproj

dotnet restore Server\ServerFunctions\WeatherStationFunctions.fsproj
dotnet build Server\ServerFunctions\WeatherStationFunctions.fsproj